version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gw  # API Gateway dizininizin yolu
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./news-app-frontend  # Next.js dizininizin yolu
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api-gateway:5000/api/news  # API Gateway URL'si
    depends_on:
      - api-gateway
